/**
 * @file ルートレイアウト
 * @description アプリケーション全体のレイアウトを定義します。メタデータとプロバイダーの設定を含みます。
 */

import 'dayjs/locale/ja'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        <main className="flex min-h-screen w-full items-start justify-start p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
